# vpsAdmind config file

:db:
    :host: localhost
    :user: vpsadmin
    :pass: password
    :name: vpsadmin
    :retry_interval: 30

:vpsadmin:
    :server_id: 1
    :domain: vpsfree.cz
    :netdev: eth0
    :threads: 6
    :check_interval: 1
    :status_interval: 300
    :update_vps_status: true
    :backups_mnt_dir: /mnt
    :restore_target: '/vz/private/%s.restoring'

:vz:
    :vzctl: /usr/sbin/vzctl
    :vzlist: /usr/sbin/vzlist
    :vzquota: /usr/sbin/vzquota
    :vzmigrate: /usr/sbin/vzmigrate
    :vz_root: /vz
    :vz_conf: /etc/vz

:bin:
    :cat: /bin/cat
    :df: /bin/df
    :rm: /bin/rm
    :mv: /bin/mv
    :cp: /bin/cp
    :mkdir: /bin/mkdir
    :chmod: /bin/chmod
    :tar: /bin/tar
    :scp: /usr/bin/scp
    :rdiff_backup: /usr/bin/rdiff-backup
    :rsync: /usr/bin/rsync
    :iptables: /sbin/iptables
    :ip6tables: /sbin/ip6tables

:backuper:
    :lock_interval: 30
    :mountpoint: /mnt
    :dest: /storage/vpsfree.cz/vps
    :tmp_restore: /storage/vpsfree.cz/restore
    :download: /storage/vpsfree.cz/download

:mailer:
    :smtp_server: localhost
    :smtp_port: 25

:console:
    :host: localhost
    :port: 8081

:handlers:
    Node:
        3: reboot
        4: sync_templates
    VPS:
        1001: start
        1002: stop
        1003: restart
        2002: set_params
        2003: set_params
        2004: set_params
        2005: set_params
        2006: set_params
        2007: set_params
        3001: create
        3002: destroy
        3003: reinstall
        3004: clone
        4001: migrate_offline
        4002: migrate_online
        5003: restore
        8001: features
    Backuper:
        5004: download
        5005: backup
        5006: backup
    Firewall:
        7201: reg_ips
    Mailer:
        9001: send
