# vpsAdmind sample config file
# Uncomment settings to override the defaults
#
# If you choose to override any kind of :handlers, you must specify all commands
# you want to use, as the default handlers are dropped.

:db:
    :host: localhost
    :user: vpsadmin
    :pass: password
    :name: vpsadmin
#     :retry_interval: 30

:vpsadmin:
    :server_id: 1
#     :domain: vpsfree.cz
#     :netdev: eth0
#     :threads: 6
#     :check_interval: 1
#     :status_interval: 300
#     :update_vps_status: true
#     :root: /opt/vpsadmind
#     :handlers:
#         VpsAdmin:
#             101: stop
#             102: restart
#             103: update
#         Node:
#             3: reboot
#             4: sync_templates
#             7301: create_config
#             7302: delete_config
#         VPS:
#             1001: start
#             1002: stop
#             1003: restart
#             2002: set_params
#             2003: set_params
#             2004: set_params
#             2005: set_params
#             2006: set_params
#             2007: set_params
#             2008: applyconfig
#             3001: create
#             3002: destroy
#             3003: reinstall
#             3004: clone
#             4001: migrate_offline
#             4002: migrate_online
#             8001: features
#         Backuper:
#             5002: restore_prepare
#             5003: restore_finish
#             5004: download
#             5005: backup
#             5006: backup
#             5007: exports
#         Firewall:
#             7201: reg_ips
#         Mailer:
#             9001: send
# 
# :vz:
#     :vzctl: vzctl
#     :vzlist: vzlist
#     :vzquota: vzquota
#     :vzmigrate: vzmigrate
#     :vz_root: /vz
#     :vz_conf: /etc/vz
# 
# :bin:
#     :cat: cat
#     :df: df
#     :rm: rm
#     :mv: mv
#     :cp: cp
#     :mkdir: mkdir
#     :chmod: chmod
#     :tar: tar
#     :scp: scp
#     :rdiff_backup: rdiff-backup
#     :rsync: rsync
#     :iptables: iptables
#     :ip6tables: ip6tables
#     :git: git
#     :zfs: zfs
# 
# :backuper:
#     :method: RdiffBackup
#     :lock_interval: 30
#     :mountpoint: /mnt
#     :dest: /storage/vpsfree.cz/backup
#     :tmp_restore: /storage/vpsfree.cz/restore
#     :backups_mnt_dir: /mnt
#     :restore_target: /mnt/%{node}/%{veid}.restoring
#     :restore_src: /vz/private/%{veid}.restoring
#     :download: /storage/vpsfree.cz/download
#     :zfs:
#         :zpool: storage/vpsfree.cz/backup
#         :rsync: %{rsync} -rlptgoDHX --numeric-ids --inplace --delete-after --exclude .zfs/ --exclude-from %{exclude} %{src} %{dst}
#     :exports:
#         :enabled: true,
#         :delimiter: "### vpsAdmin ###"
#         :options: ""
#         :path: /etc/exports
#         :reexport: exportfs -r
# 
# :mailer:
#     :smtp_server: localhost
#     :smtp_port: 25
# 
# :console:
#     :host: localhost
#     :port: 8081
# 
# :remote:
#     :socket: /var/run/vpsadmind.sock
#     :handlers:
#         VpsAdmin:
#             - :reload
#             - :restart
#             - :status
#             - :stop
#             - :update
