# vpsAdmind sample config file
# Uncomment settings to override the defaults
#
# If you choose to override any kind of :handlers, you must specify all commands
# you want to use, as the default handlers are dropped.

:db:
    :hosts:
      - localhost
    :user: vpsadmin
    :pass: password
    :name: vpsadmin
#     :retry_interval: 30
#     :ssl: false

:vpsadmin:
    :server_id: 1
#     :domain: vpsfree.cz
#     :netdev: eth0
#     :threads: 6
#     :urgent_threads: 6
#     :check_interval: 1
#     :status_interval: 60
#     :resources_interval: 300
#     :transfers_interval: 10
#     :update_vps_status: true
#     :track_transfers: true
#     :root: /opt/vpsadmind
#     :init: true
#     :handlers:
#         VpsAdmin:
#             101: stop
#             102: restart
#             103: update
#         Node:
#             3: reboot
#             4: sync_templates
#             5: gen_known_hosts
#             7301: create_config
#             7302: delete_config
#         VPS:
#             1001: start
#             1002: stop
#             1003: restart
#             2002: passwd
#             2003: set_params
#             2004: set_params
#             2005: set_params
#             2006: set_params
#             2007: set_params
#             2008: applyconfig
#             3001: create
#             3002: destroy
#             3003: reinstall
#             4002: migrate_online
#             5301: nas_mounts
#             5302: nas_mount
#             5303: nas_umount
#             5304: nas_remount
#             8001: features
#         Clone:
#             3004: local_clone
#             3005: remote_clone
#         Migration:
#             4011: prepare
#             4021: migrate_part1
#             4022: migrate_part2
#             4031: cleanup
#         Storage:
#             5201: create_export
#             5202: update_export
#             5203: delete_export
#         Backuper:
#             5001: restore_prepare
#             5002: restore_restore
#             5003: restore_finish
#             5004: download
#             5005: backup
#             5006: backup
#             5007: exports
#             5011: backup_snapshot
#             5021: replace_backups
#         Firewall:
#             7201: reg_ips
#         Mailer:
#             9001: send
# 
# :vz:
#     :vzctl: vzctl
#     :vzlist: vzlist
#     :vzquota: vzquota
#     :vzmigrate: vzmigrate
#     :vz_root: /vz
#     :vz_conf: /etc/vz
# 
# :bin:
#     :cat: cat
#     :df: df
#     :rm: rm
#     :mv: mv
#     :cp: cp
#     :mkdir: mkdir
#     :rmdir: rmdir
#     :chmod: chmod
#     :tar: tar
#     :scp: scp
#     :rdiff_backup: rdiff-backup
#     :rsync: rsync
#     :iptables: iptables
#     :ip6tables: ip6tables
#     :git: git
#     :zfs: zfs
#     :mount: mount
#     :umount: umount
#     :uptime: uptime
#     :uname: uname
#     :hostname: hostname
#     :ssh_keygen: ssh-keygen
#     :exportfs: exportfs
# 
# :vps:
#     :clone:
#         :rsync: %{rsync} -rlptgoDH --numeric-ids --inplace --delete-after %{src} %{dst}
#     :zfs:
#         :root_dataset: vz/private
#         :sharenfs: ~
#     :migration:
#         :rsync: %{rsync} -rlptgoDH --numeric-ids --inplace --delete-after %{src} %{dst}
# 
# :node:
#     :pubkey:
#         :types:
#             - rsa
#             - dsa
#         :path: /etc/ssh/ssh_host_%{type}_key.pub
#     :known_hosts: /root/.ssh/known_hosts
# 
# :storage:
#     :method: Zfs
#     :update_status: true
# 
# :backuper:
## RdiffBackup or Zfs
#     :method: RdiffBackup
#     :lock_interval: 30
#     :mountpoint: /mnt
#     :tmp_restore: /storage/vpsfree.cz/restore
#     :backups_mnt_dir: /mnt
#     :restore_target: /mnt/%{node}/%{veid}.restoring
#     :restore_src: /vz/private/%{veid}.restoring
#     :download: /storage/vpsfree.cz/download
#     :zfs:
#         :rsync: %{rsync} -rlptgoDH --numeric-ids --inplace --delete-after --exclude .zfs/ --exclude-from %{exclude} %{src} %{dst}
## How many backups to store, unit is a day
#     :store:
## Minimum number of backups that must be stored
#         :min_backups: 14
## Maximum number of backups to store
#         :max_backups: 20
## Max age, older backups will be kept only if you have less or equal number of backups than :min_backups
#         :max_age: 14
#     :restore:
#         :zfs:
#             :head_rsync: %{rsync} -rlptgoDH --numeric-ids --inplace --delete-after %{src} %{dst}
#         :exttozfs:
#             :rsync: %{rsync} -rlptgoDH --numeric-ids --inplace --delete-after --exclude .zfs/ %{src} %{dst}
#     :exports:
#         :enabled: true,
#         :delimiter: "### vpsAdmin ###"
#         :options: ""
#         :path: /etc/exports
#         :reexport: exportfs -r
# 
# :mailer:
#     :smtp_server: localhost
#     :smtp_port: 25
# 
# :console:
#     :host: localhost
#     :port: 8081
# 
# :remote:
#     :socket: /var/run/vpsadmind.sock
#     :handlers:
#         VpsAdmin:
#             - :reload
#             - :restart
#             - :status
#             - :stop
#             - :update
#             - :kill
#             - :reinit
#             - :refresh
#             - :install
#             - :get
#             - :set
